name: Repository Dispatch Workflow

on:
  push

jobs:
  run-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Workflow
        run: echo "Workflow triggered by repository dispatch event."
